# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
t=s.split()
print(t)

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
txt="The diameter of {} is {} kilometers.".format(planet,diameter)
print(txt)

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d["k1"][3]["tricky"][3]["target"][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
tmp=np.zeros(10)
print(tmp)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [9]:
tmp=np.ones(10)*5
print(tmp)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [10]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [11]:
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [12]:
a=np.array([1,2,3])
b=np.array([4,5,6])
tmp=np.concatenate((a,b),axis=0)

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [13]:
import pandas as pd


In [14]:
data=[['a',1],['b',2],['c',3]]
df=pd.DataFrame(data,columns=['x','y'])
df

x  y
0  a  1
1  b  2
2  c  3

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [15]:
dates = pd.date_range(start='1/1/2023',end='2/10/2023')
lists = []
for i in dates:
  lists.append(i.strftime('%d-%m-%y'))
print(lists)  

['01-01-23', '02-01-23', '03-01-23', '04-01-23', '05-01-23', '06-01-23', '07-01-23', '08-01-23', '09-01-23', '10-01-23', '11-01-23', '12-01-23', '13-01-23', '14-01-23', '15-01-23', '16-01-23', '17-01-23', '18-01-23', '19-01-23', '20-01-23', '21-01-23', '22-01-23', '23-01-23', '24-01-23', '25-01-23', '26-01-23', '27-01-23', '28-01-23', '29-01-23', '30-01-23', '31-01-23', '01-02-23', '02-02-23', '03-02-23', '04-02-23', '05-02-23', '06-02-23', '07-02-23', '08-02-23', '09-02-23', '10-02-23']


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [16]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [17]:
data=pd.DataFrame(lists,columns=["Col1","Col2","Col3"])
print(data)

   Col1 Col2  Col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24
